### ISSUE TITLE
Wiring diagram

### ISSUE THREAD

**Issue by komainu85** [phofman/win10-iot#1]
Do you have a wiring diagram for the seven segment display by any chance?

https://github.com/phofman/win10-iot/blob/8f5c24d5d8ce44e143324f007e1f885817e93c38/01_leds/7DigitDisplay/StartupTask.cs

**Comment by phofman** [comment]
I don't have it right now, but can draw one, if you like.

**Comment by komainu85** [comment]
If that's not a lot of trouble that would be really helpful, thanks.

**Comment by phofman** [comment]
Take a look at [Schematics folder](/phofman/win10-iot/tree/master/01_leds/Schematics) for asked wiring diagram of 7-segment 4-digits display. Should do the trick ;)

**Comment by komainu85** [comment]
That's awesome, thank you for this :)
